# Generated by Django 2.1.5 on 2019-01-16 14:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Device',
            fields=[
                ('device_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=250, verbose_name='Name')),
                ('mac_address', models.CharField(blank=True, max_length=20, unique=True)),
                ('description', models.TextField(blank=True, max_length=2048, verbose_name='Description')),
                ('added', models.DateTimeField(auto_now_add=True, verbose_name='Added')),
                ('last_modified', models.DateTimeField(auto_now_add=True, verbose_name='Added')),
                ('status', models.CharField(choices=[('new', 'New'), ('active', 'In use'), ('shelf', 'Not in use'), ('broken', 'Broken'), ('repair', 'In repair'), ('lost', 'Lost'), ('sold', 'Sold'), ('scrapped', 'Scrapped')], db_index=True, default='new', max_length=16, verbose_name='Status')),
                ('ownership', models.CharField(choices=[('org', 'Organisation'), ('vendor', 'Vendor (leasing etc)'), ('user', 'User'), ('ext', 'External organisation')], db_index=True, default='org', max_length=16, verbose_name='Ownership')),
                ('warranty_until', models.DateField(blank=True, verbose_name='Warranty until')),
            ],
        ),
        migrations.CreateModel(
            name='DeviceModel',
            fields=[
                ('model_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=250, null=True)),
                ('device_type', models.CharField(choices=[('desktop', 'Desktop'), ('laptop', 'Laptop'), ('phone', 'Phone'), ('handheld', 'Handheld (tablet etc)'), ('iot', 'IoT device (fridge, lamp controller etc)'), ('other', 'Other')], db_index=True, default='other', max_length=16, verbose_name='Device type')),
                ('comments', models.TextField(verbose_name='Comments')),
            ],
        ),
        migrations.CreateModel(
            name='Manufacturer',
            fields=[
                ('manufacturer_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=250, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Vendor',
            fields=[
                ('vendor_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=250, null=True, verbose_name='Name')),
                ('address', models.CharField(blank=True, max_length=250, null=True, verbose_name='Address')),
                ('postal_code', models.IntegerField(blank=True, null=True, verbose_name='Postal code')),
                ('city', models.CharField(blank=True, max_length=100, null=True, verbose_name='City')),
                ('phone_number', models.CharField(blank=True, max_length=30, null=True, verbose_name='Phone number')),
            ],
        ),
        migrations.AddField(
            model_name='devicemodel',
            name='manufacturer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='device.Manufacturer', verbose_name='Manufacturer'),
        ),
        migrations.AddField(
            model_name='device',
            name='model',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='device.DeviceModel', verbose_name='Model'),
        ),
        migrations.AddField(
            model_name='device',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Owner'),
        ),
    ]
