# Generated by Django 2.1.5 on 2019-01-23 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('device', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendor',
            name='country',
            field=models.CharField(blank=True, max_length=50, verbose_name='Country'),
        ),
        migrations.AlterField(
            model_name='device',
            name='warranty_until',
            field=models.DateField(blank=True, null=True, verbose_name='Warranty until'),
        ),
    ]
